In [3]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [7]:

arr1=np.array([1,2,3,4,5])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
type(arr1)

numpy.ndarray

In [8]:
print(arr1.ndim)

1


In [12]:
arr2=np.array([[1,2,3],[4,5,6]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(arr2.ndim)

2


In [19]:
arr3=np.zeros((3,5))

In [20]:
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
arr5=np.ones((3,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr=np.array(55)
arr

array(55)

In [8]:
#accessing element
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [9]:
print(arr1[3])

4


In [10]:
arr1[2]

np.int64(3)

In [11]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
#second element on 1st row
arr2[0,1]

np.int64(2)

In [14]:
arr2[1,3]

np.int64(8)

In [10]:
arr3=np.array([1,2,3,4,5,6,7,8,9])
print(arr3[1:5])

[2 3 4 5]


In [16]:
arr3[:4]

array([1, 2, 3, 4])

In [17]:
arr3[7:]

array([8, 9])

In [ ]:
#start,stop,gap

In [11]:
arr3[0:5:2]

array([1, 3, 5])

In [19]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2.shape)

(2, 4)


In [12]:
#reshape rows
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
newarr=arr.reshape(2,6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
newarr=arr.reshape(2,6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [27]:
#iterating arrays
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [28]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr2:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [4]:
matrix2=np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [5]:
matrix6=np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
#trignometric functions
print('sine funtion:',np.sin(4))
print('cosine funtion:',np.cos(4))
print('tan funtion:',np.tan(4))

sine funtion: -0.7568024953079282
cosine funtion: -0.6536436208636119
tan funtion: 1.1578212823495777


In [9]:
np.exp(2)

np.float64(7.38905609893065)

In [11]:
arr5=np.array([2,4,6])
np.exp(arr5)
              

array([  7.3890561 ,  54.59815003, 403.42879349])

In [13]:
np.log(2)

np.float64(0.6931471805599453)

In [14]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [15]:
l1=[1,2,3,4]
l2=[5,6,7,8]
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)
arr8 = np.arange(3,8)
print('arr8:', arr8)
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7 ** arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]
Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


In [23]:
# opreations of matrix
matrix7=np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8=np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\Ayushi\AppData\Local\Temp\ipykernel_24276\2604038799.py:4: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


In [25]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)
matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# taking linear algebra matrix multiplication (
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [27]:
#transpose
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])